import * as esbuild from 'esbuild';
const DEFAULT_EXTENSION = /\.(jsx)$/;

const makeBanner = (timestamp) => {
  return `// Autogenerated by verso at ${timestamp.toISOString()}

import { h as VersoElement, Fragment as VersoFragment } from "@verso/core";`;
};

export const compile = async (code) => {
  const result = await esbuild.transform(code, {
    banner: makeBanner(new Date()),
    jsxFactory: 'VersoElement',
    jsxFragment: 'VersoFragment',
    loader: 'jsx',
  });

  return result.code;
};

export const versoVitePlugin = ({ extension = DEFAULT_EXTENSION } = {}) => {
  return {
    name: 'verso',
    enforce: 'pre',

    async transform(src, id) {
      if (extension.test(id)) {
        const res = await compile(src);

        return {
          code: res,
          map: null, // provide source map if available
        };
      }
    },
  };
};
