import * as esbuild from 'esbuild';

const makeBanner = (timestamp) => {
  return `// Autogenerated by verso at ${timestamp.toISOString()}

import { h, Fragment } from "@verso/core";`;
};

export const compile = async (code) => {
  const result = await esbuild.transform(code, {
    banner: makeBanner(new Date()),
    jsxFactory: 'h',
    jsxFragment: 'Fragment',
    loader: 'jsx',
  });

  return result.code;
};
